// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngubohdyfywtwsssfkoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndWJvaGR5Znl3dHdzc3Nma29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTIyOTMsImV4cCI6MjA2NTUyODI5M30.aJzxMD6fHAFDOZuxCTrIKWH6o6Q9SyGf5LME7vzqJIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);